config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  post 'follows', to: 'follows#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :follows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def create
        user = User.first #仮に最初のユーザとするが，本アプリではログイン中のユーザを取得する
        user.follows << Follow.new(to: params[:to])
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    User.create(name: params[:user][:name])
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AAA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |e| %>
    <hr>
    <p>
    user.id: <%= e.id %>
    user.name: <%= e.name %>
    <%= link_to 'フォローする', follows_path(to: e.id), method: :post %>
    </p>
    フォローしているアカウント：
    <% e.follows.each do |ee| %>
        <%= User.find(ee.to).name %>
    <% end %>
<% end %>

<%= link_to '新規追加', new_user_path %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: :create} do |f| %>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name %>
    <%= f.submit '登録' %>
<% end %>